name: tw
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.7.2
  - libffi=3.4.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.11.9
  - setuptools=72.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - tzdata=2024a
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - bcrypt==4.2.0
      - blinker==1.8.2
      - cffi==1.17.1
      - click==8.1.7
      - colorama==0.4.6
      - cryptography==43.0.1
      - datetime==5.5
      - flask==3.0.3
      - flask-sqlalchemy==3.1.1
      - greenlet==3.1.0
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - jwt==1.3.1
      - markupsafe==2.1.5
      - psycopg2-binary==2.9.9
      - pycparser==2.22
      - pyjwt==2.9.0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - sqlalchemy==2.0.34
      - tabulate==0.9.0
      - typing-extensions==4.12.2
      - werkzeug==3.0.4
      - zope-interface==7.0.3
